/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_RPC_URL: process.env.NEXT_PUBLIC_RPC_URL,
    NEXT_PUBLIC_PRICEFEEDL1_ADDRESS: process.env.NEXT_PUBLIC_PRICEFEEDL1_ADDRESS,
    NEXT_PUBLIC_POSITIONS_ADDRESS: process.env.NEXT_PUBLIC_POSITIONS_ADDRESS,
    NEXT_PUBLIC_MARKET_ADDRESS: process.env.NEXT_PUBLIC_MARKET_ADDRESS,
    NEXT_PUBLIC_LIQUIDITYPOOLFACTORY_ADDRESS: process.env.NEXT_PUBLIC_LIQUIDITYPOOLFACTORY_ADDRESS,
    NEXT_PUBLIC_FEEMANAGER_ADDRESS: process.env.NEXT_PUBLIC_FEEMANAGER_ADDRESS,
    NEXT_PUBLIC_WRAPPER_ADDRESS: process.env.NEXT_PUBLIC_WRAPPER_ADDRESS,
  },
};

export default nextConfig;

